### ISSUE TITLE
Custom text for jvFloat

### ISSUE THREAD

**Issue by nicohvi** [maman/JVFloat.js#21]
Hi, love the library!

Would it perhaps be interesting to add a custom text to be added to the jfFloat-label? Something like this, perhaps?

```javascript
function getPlaceholderText($el) {
  var text = $el.data('float-text') || $el.attr('placeholder');
  
  if (typeof text == 'undefined') {
    text = $el.attr('title');
  }

  return text;
}
```

```HTML
<input id="username" type="text" data-float-text="Be creative! (username)" >
```

**Comment by maman** [comment]
you can already use the custom text by using the `placeholder` attribute, which explain what the `input` is for. If you want to use another attribute to set the float label text, feel free to fork my library and make your own adjustments :+1:
