### ISSUE TITLE
Trigger placeholder to label on browser-autofill

### ISSUE THREAD

**Issue by doublejosh** [maman/JVFloat.js#26]
Many form fields will end up auto-filled by the browser.  The placeholder should be trigger by values being added, not just focus events.

**Comment by doublejosh** [comment]
Got around this with some custom code...

```javascript
$.each($('.form-input__text'), function() {
  $(this).on('focus blur change input', function touchedInput() {
    if ($(this).val() !== '') {
      $(this).siblings('label').addClass('active');
    }
  });
});

**Comment by maman** [comment]
hey, sorry for the super-late follow ups. glad you can workaround the problems :+1:
